# Sync code to github repository and deploy code on production
image: composer:2.0

pipelines:
  branches:
    production-softpro:
      - step:
          name: Sync Single Branch to GitHub
          image: alpine/git:latest
          script:
            - mkdir -p ~/.ssh
            - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            - git remote add github git@github.com:pacificcoasttitle/TransactionDeskClone.git
            - git push github production-softpro

    # Deploy via SSH
    production:
      - step:
          name: Deploy to Server
          script:
            - pipe: atlassian/ssh-run:0.3.0
              variables:
                SSH_USER: $PCT_SSH_USER
                SERVER: $PCT_HOST
                PORT: $PCT_PORT
                MODE: 'command'
                COMMAND: $PCT_PROD_SH
